import 'package:flutter/material.dart';

const primaryColor = Color(0xFF3B878E);
const letsGetStartedButtonColor = Color(0xFF202022);
const dropDownBackgroundColor = Color(0xFFECF3F9);
//const backgroundColor = Color(0xFFBFF2B9);
const backgroundColor = Color(0xFFFFFFFF);
const buttonBGColor = Color(0xFF1A3154);
const circularProgressColor = Color(0xFF1C75BC);
const blutoothDialogTitleColor = Color(0xFF0F0F11);
const blutoothDialogTxtColor = Color(0xFF000000);
const bluetoothCancelBtnTxtColor = Color(0xFF090909);
const bluetoothCancelBtnBackColor = Color(0xFFC7CACE);
const bluetoothConnectBtnBackColor = Color(0xFF1A3154);
const bluetoothConnectBtncolor = Color(0xFFFFFFFF);
const bluetoothDeviceInActiveColor = Color(0xFF797979);
const dateBackgroundColor = Color(0xFFECF3F8);
const selectDayBackgroundColor = Color(0xFFE4F5F5);
const reportBackgroundColor = Color(0xFFF5F5F5);
const reportTabColor = Color(0xFFC5FFBF);
const tripColumnBarColor = Color(0xFFF9AF75);
const tripColumnBar1Color = Color(0xFFBFF2B9);
const tableHeaderColor = Color(0xFF9097BC);
const commonBackgroundColor = Color(0xFFF3FFFB);
const dateColor = Color(0xFF6B6363);
const dividerColor = Color(0xFFDADADA);
const checkColor = Color(0xFF41C1C8);
const userFeedbackBtnColor = Color(0xFFDE6767);
const reportsNewTabColor = Color(0xFFE4F5F5);
const floatingBtnColor = Color(0xFFDB2667);
const reportFilterBackColor = Color(0xFFF4F6F8);
const reportDropdownColor = Color(0xFFE4E8F0);
const reportTripsListBackColor = Color(0xFFFAFDFF);
const reportTripsListColor = Color(0xFFF5FBF9);
const blueColor = Color(0xFF2663DB);
const uploadTripBtnColor = Color(0xFFE19C16);
const routeMapBtnColor = Color(0xFF67C6C7);
const endTripBtnColor = Color(0xFFFF2020);
const statusTagCompletedColor = Color(0xFF5BC096);
const statusTagProgressColor = Color(0xFFE19C16);
const authBtnColors = Color(0xFFDFF9F9);
const bottomNavColor = Color(0xFFF8FFFF);
const filterByTripTxtColor = Color(0xFF979797);
const deleteTripBtnColor = Color(0xFFFF2020);
const inProgressTrip = Color(0xFFFDBF21);
const skipAndContinueBtnColor = Color(0xFFD1E0FC);


