name: performarine

description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
#  uuid: ^3.0.7
  objectid: 2.0.0
 # font_awesome_flutter: ^10.2.1
  path: ^1.8.0
#  flutter_speed_dial: ^6.2.0
  sqflite: ^2.0.1
  expandable: ^5.0.1
  email_validator: ^2.0.1
  #country_picker: ^2.0.16
  #pin_code_fields: ^7.4.0
  #images_picker: ^1.2.11
  lottie:
  #sliding_up_panel: ^2.0.0+1
  #step_progress_indicator: ^1.0.2
  package_info_plus: ^3.0.1
  get: ^4.6.5
  #animate_do: ^3.0.2
  #smooth_page_indicator: ^1.0.0+2
  provider: ^6.0.4
  http: ^0.13.5
  #location: ^4.4.0
#  geocoding: ^2.0.5
  permission_handler: 10.3.0
  device_info_plus: ^8.0.0
  google_sign_in: ^5.4.2
  firebase_core: ^2.15.0
#  sign_in_with_apple: ^4.1.0
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  geolocator: ^9.0.2
  url_launcher: ^6.0.20
  path_provider: ^2.0.9
  sensors_plus: ^2.0.1
  flutter_archive: ^5.0.0
  dio: ^4.0.6
  #open_file: ^3.2.1
  #mime: ^1.0.1
  intl: ^0.18.0
  #image_cropper: ^3.0.1
  file_picker: ^5.2.2
  image_picker: ^0.8.6
  #image_gallery_saver:
  #flutter_background_service: ^2.4.6
  flutter_local_notifications: ^12.0.3
  #flutter_background_service_android: ^3.0.3
  #flutter_background_service_ios: ^2.4.0
  flutter_phoenix: ^1.1.0
  connectivity_plus: ^2.3.9
  #timezone: ^0.9.1
  #app_settings: ^4.2.0
  http_parser: ^4.0.2
  flutter_sensors: ^1.0.1
  status_stepper: ^1.0.0
  flutter_image_compress: ^1.1.3
  flutter_blue_plus: ^1.5.2
  bluetooth_enable_fork: ^0.1.6
  table_calendar: ^3.0.0
  syncfusion_flutter_charts: 21.2.4
  background_locator_2:
    path: ./performarine_location_tracker
  webview_flutter: ^2.0.14
  flutter_easyloading: ^3.0.5
  #airplane_mode_checker: ^2.0.0
  #location_permissions: ^3.0.0+1
  uni_links: ^0.5.1
  firebase_crashlytics: ^3.3.3
  wakelock: ^0.6.2
  screenshot: ^1.2.0
  logger: ^1.4.0
  workmanager: ^0.5.1
  flutter_slidable: ^3.0.0
  firebase_remote_config: 3.0.15
  flutter_secure_storage: ^8.0.0
  firebase_core_platform_interface: ^4.8.0
  firebase_remote_config_platform_interface: ^1.4.4
  flutter_map: ^4.0.0
  latlong2: ^0.8.2
  flutter_xlider: ^3.5.0
  animated_bottom_navigation_bar: ^1.2.0
  dropdown_button2: ^2.3.8


dependency_overrides:
  ffi: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Flutter Launcher Icons
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  ios: true
  android: true
  image_path: "assets/images/app_logo.png"



flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/lottie/
    - assets/icons/
    - assets/map/anholt_osmbright/12/2177/
    - assets/map/anholt_osmbright/12/2178/
    - assets/map/anholt_osmbright/12/2179/
    - assets/map/anholt_osmbright/12/2180/
    - assets/map/anholt_osmbright/12/2181/
    - assets/map/anholt_osmbright/13/4354/
    - assets/map/anholt_osmbright/13/4355/
    - assets/map/anholt_osmbright/13/4356/
    - assets/map/anholt_osmbright/13/4357/
    - assets/map/anholt_osmbright/13/4358/
    - assets/map/anholt_osmbright/13/4359/
    - assets/map/anholt_osmbright/13/4360/
    - assets/map/anholt_osmbright/13/4361/
    - assets/map/anholt_osmbright/13/4362/
    - assets/map/anholt_osmbright/13/4363/
    - assets/map/anholt_osmbright/14/8709/
    - assets/map/anholt_osmbright/14/8710/
    - assets/map/anholt_osmbright/14/8711/
    - assets/map/anholt_osmbright/14/8712/
    - assets/map/anholt_osmbright/14/8713/
    - assets/map/anholt_osmbright/14/8714/
    - assets/map/anholt_osmbright/14/8715/
    - assets/map/anholt_osmbright/14/8716/
    - assets/map/anholt_osmbright/14/8717/
    - assets/map/anholt_osmbright/14/8718/
    - assets/map/anholt_osmbright/14/8719/
    - assets/map/anholt_osmbright/14/8720/
    - assets/map/anholt_osmbright/14/8721/
    - assets/map/anholt_osmbright/14/8722/
    - assets/map/anholt_osmbright/14/8723/
    - assets/map/anholt_osmbright/14/8724/
    - assets/map/anholt_osmbright/14/8725/
    - assets/map/anholt_osmbright/14/8726/
    - assets/map/anholt_osmbright/14/8727/
    - assets/map/epsg3413/amsr2.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700

    - family: Inter
      fonts:
        - asset: assets/fonts/inter.ttf

    - family: ReemKufiInk
      fonts:
        - asset: assets/fonts/ReemKufiInk-Regular.ttf

    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Bold.ttf
        - asset: assets/fonts/Outfit-Medium.ttf
        - asset: assets/fonts/Outfit-Regular.ttf
